# Generated by Django 4.0.6 on 2022-08-04 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_price_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
