# Generated by Django 4.0.6 on 2022-08-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_profile_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postal',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
