# Generated by Django 4.0.6 on 2022-08-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
