# Generated by Django 4.0.6 on 2022-08-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_likeforproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeforproduct',
            old_name='target',
            new_name='product',
        ),
    ]
